@startuml Graph

!include ../domain/IGraph.puml

class Graph {
    - vertices: HashSet<IVertex> {readOnly}
    - edges: HashSet<IEdge> {readOnly}
    - adjacencyMap: Dictionary<IVertex, HashSet<IVertex>> {readOnly}
    
    - Graph(int verticesCount)
    + Empty(verticesCount: int): IGraph {static}
}

Graph ..|> IGraph

@enduml