@startuml FileGraphLogger

!include ../domain/IGraphLogger.puml

class FileGraphLogger {
    - fileStream: FileStream
    - streamWriter: StreamWriter
    - isDisposed: bool
    - filePath: string
    - dirPath: string

    + FileGraphLogger(filepath: string)
    + Dispose(): void
}

FileGraphLogger ..|> IGraphLogger

@enduml
