@startuml Graph

!include ../domain/IGraph.puml

class Graph {
    - vertices: HashSet<IVertex>
    - edges: HashSet<IEdge>
    - adjacencyMap: Dictionary<IVertex, HashSet<IVertex>>

    - Graph(verticesCount: int)
    + Empty(verticesCount: int): IGraph {static}
}

Graph ..|> IGraph

@enduml
