@startuml GraphPart

!include ../domain/IGraphPart.puml

class GraphPart {
    - parent: IGraph
    - vertices: HashSet<IVertex>

    + GraphPart(parent: IGraph)
}

GraphPart ..|> IGraphPart

@enduml
