@startuml IGraphPartition

interface IGraphPartition {
    + Graph: IGraph {readOnly}
    + PartsCount: int {readOnly}
    + Parts: IEnumerable<IGraphPart> {readOnly}

    + SwapVertices(first: IVertex, second: IVertex): void
    + CalculateGain(first: IVertex, second: IVertex)
    + GetCrossEdgesCount(): int
    + GetPart(vertex: IVertex): IGraphPart
}

@enduml