@startuml IGraphPartitionStats

interface IGraphPartitionStats {
    + CrossEdgesCount: int {readOnly}
    + GenerationTimeMs: int {readOnly}
    + IterationsCount: int {readOnly}

    + Partition: IGraphPartition {readOnly}
}

@enduml